apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  darts.toml: |
    [rule.darts]
    enabled-chats = [
        133399998,
        -1001604571340,
        -1001725586482,
    ]

    [rule.darts.133399998]
    emojis = ["🎯"]
    cooldown.seconds = 5

    [rule.darts.-1001604571340]
    emojis = ["🎯"]

    [rule.darts.-1001725586482]
    emojis = ["🎰"]

  lemons.toml: |
    [rule.lemons]
    enabled-chats = [
        -1001725586482,
        -1001587782443,
    ]

  premium.toml: |
    [rule.premium]
    enabled-chats = [
        -1001649059583,
    ]

  slash.toml: |
    [rule.slash]
    enabled-chats = [
        133399998,
        -1001458632057,
        -1001473841450,
    ]

  smartypants.toml: |
    [rule.smartypants]
    model-name = "openai/gpt-image-1"
    enabled-chats = [
        133399998,
        -1002264342797,
    ]
