apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  dice.yaml: |
    forwardTo: -1001587782443
    allowedEmojis:
      -1001725586482:
        - 🎰

  lemons.yaml: |
    enabledChats:
      - -1001725586482
      - -1001587782443

  slash.txt: |
    133399998
    -1001458632057
    -1001473841450

  darts.yaml: |
    133399998:
      emojis:
        - 🎯
      cooldown:
        seconds: 5
    -1001604571340:
      emojis:
        - 🎯

  premium.yaml: |
    enabledChats:
      - 133399998
      - -1001649059583

  smartypants.yaml: |
    modelName: "openai/gpt-image-1"
    enabledChats:
      - 133399998
      - -1002264342797
