apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-horoscope-sub
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy:
   type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-horoscope-sub
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-horoscope-sub
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config
        - name: gcp-secrets
          secret:
            secretName: {{ .Release.Name }}-gcp-secrets
      containers:
        - name: app
          image: {{ .Values.image }}:{{ .Values.appVersion }}
          args:
            - --subscribe-horoscopes
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /gcp
              name: gcp-secrets
              readOnly: true
          env:
            - name: STATE_NAME_PREFIX
              value: {{ .Release.Name }}-state-
            - name: STATE_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: CONFIG_DIR
              value: /config
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-gcp
            - secretRef:
                name: {{ .Release.Name }}-secrets
            - secretRef:
                name: {{ .Release.Name }}-rule-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
