---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-rule-secrets
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: scaleway-prep-moderator-bot
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "name:rules"
      rewrite:
        - regexp:
            source: "(.+)"
            target: "RULE__$1"
