---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-rule-secrets
spec:
  secretStoreRef:
    name: doppler-prep
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-rule-secrets
  dataFrom:
    - find:
        path: "MODERATOR_RULE_"
      rewrite:
        - regexp:
            source: "^MODERATOR_RULE_(.+)$"
            target: "RULE_$1"
