---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
spec:
  secretStoreRef:
    name: doppler-prep
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-secrets
  dataFrom:
    - find:
        path: "MODERATOR_BASE_"
      rewrite:
        - regexp:
            source: "MODERATOR_BASE_(.+)"
            target: "$1"
