---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
spec:
  secretStoreRef:
    name: scaleway-prep-moderator-bot
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "name:manual-secrets"
