---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-update-handler
  labels:
    app: {{ .Release.Name }}-update-handler
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}-update-handler
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-update-handler
    spec:
      terminationGracePeriodSeconds: 60
      serviceAccountName: {{ .Release.Name }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config
      containers:
        - name: app
          image: {{ .Values.image }}:{{ .Values.appVersion }}
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
          volumeMounts:
            - mountPath: /config
              name: config
          env:
            - name: CONFIG_DIR
              value: /config
            - name: ADMIN_USER_ID
              value: "{{ .Values.telegram.adminUserId }}"
            - name: STATE__REDIS__USERNAME
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: username
            - name: STATE__REDIS__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
            - name: STATE__REDIS__HOST
              value: "redis.prep-redis-state"
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secrets
            - secretRef:
                name: {{ .Release.Name }}-rule-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
