apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-gcp
data:
  GOOGLE_CLOUD_PROJECT: prep-telegram-bots
  GOOGLE_APPLICATION_CREDENTIALS: /gcp/sa.json
  GOOGLE_PUBSUB_SUBSCRIPTION: moderator-horoscopes
