apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-horoscope-sub
spec:
  strategy:
   type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.name }}-horoscope-sub
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-horoscope-sub
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ .Values.name }}-config
        - name: gcp-secrets
          secret:
            secretName: {{ .Values.name }}-gcp-secrets
      containers:
        - name: app
          image: {{ .Values.image }}
          args:
            - --subscribe-horoscopes
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /gcp/sa.json
              name: gcp-secrets
              subPath: GSA_JSON
              readOnly: true
          env:
            - name: CONFIG_DIR
              value: /config
          envFrom:
            - configMapRef:
                name: {{ .Values.name }}-gcp
            - secretRef:
                name: {{ .Values.name }}-secrets
