apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.name }}-secrets
stringData:
  ADMIN_USER_ID: "{{ .Values.telegram.adminUserId }}"
  SENTRY_DSN: "{{ .Values.sentry.dsn }}"
  TELEGRAM_API_KEY: {{ .Values.telegram.apiKey }}
