---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-update-handler
  labels:
    app: {{ .Release.Name }}-update-handler
spec:
  replicas: 1
  serviceName: {{ .Release.Name }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-update-handler
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-update-handler
    spec:
      serviceAccountName: {{ .Release.Name }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config
      containers:
        - name: app
          image: {{ .Values.image }}
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - mountPath: /config
              name: config
          env:
            - name: CONFIG_DIR
              value: /config
            - name: STATE_NAME_PREFIX
              value: {{ .Release.Name }}-state-
            - name: STATE_NAMESPACE
              value: {{ .Release.Namespace }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secrets
