---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-update-handler
  labels:
    app: {{ .Values.name }}-update-handler
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.name }}-update-handler
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-update-handler
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ .Values.name }}-config
      containers:
        - name: app
          image: {{ .Values.image }}
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 40m
              memory: 64Mi
          volumeMounts:
            - mountPath: /config
              name: config
          env:
            - name: CONFIG_DIR
              value: /config
          envFrom:
            - secretRef:
                name: {{ .Values.name }}-secrets
